spring:
  # mysql 설정
  datasource:
    url: jdbc:mysql://배포ip:3306/idealstudy
    #    url: jdbc:mysql://172.17.129.27:3306/idealstudy (성진 wsl 주소)
  # redis 설정
  data:
    redis:
      host: 배포ip

server:
  backend-domain-url: http://배포ip:8080
  dev: false