spring:
  application:
    name: mvp

  profiles:
    group:
      development:
        - "dev"
        - "private"
      deployment:
        - "prod"
        - "private"
      test:
        - "test"
    active: development

  jpa:
    hibernate:
      ddl-auto: update # 일단 init.sql 보다 엔티티를 존중함
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # 파일 업로드 크기 제어
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 250MB

  sql:
    init:
      mode: always # 서버 실행시 항상 data.sql 실행
      continue-on-error: true # data.sql 삽입오류시에도 서버 종료하지 않도록

upload:
  path: src/main/resources/static/upload-materials/

  #  파일업로드 // 향후 시크릿으로 관리 대상
  materials-path: src/main/resources/static/upload-materials/
  exam-path: src/main/resources/static/upload-exam/
  assignment-path: src/main/resources/static/upload-assignment/
  classroom-thumbnail-path: src/main/resources/static/upload-classes-thumbnail/


# 로깅 관련 설정은 logback-spring-server.xml 에서 세밀하게 관리
#logging:
#  level:
#    root: info
#    org.springframework.security.web: trace
#  file: # 스프링 서버에서 남긴 이 로그를 파일에 저장
#    name: /var/log/spring-logs/spring-server.log

springdoc:
  cache:
    disabled: true