spring:
  application:
    name: mvp

  profiles:
    active: dev  # 기본 프로파일을 'dev'로 설정

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.21.138.60:3306/idealstudy
#    username: manager
#    password: manager

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org.springframework.security.web: trace