spring:
  application:
    name: mvp

  profiles:
    group:
      development:
        - "dev"
        - "private"
      deployment:
        - "prod"
        - "private"
    active: development

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org.springframework.security.web: trace