spring:
  # mysql 연결설정
  datasource:
    url: jdbc:mysql://mysql-db:3306/idealstudy

# redis 연결설정 (RedisConfig 에서 커스텀하게 들어감)
redis:
  hostname: redis-db  # redis 컨테이너의 서비스 이름을 지정
  port: 6379          # 기본 Redis 포트

server:
  backend-domain-url: http://localhost:8080 # 이메일 인증시 리다이렉트될 주소 TODO: 향후 도메인으로 변경
  dev: false