# 로컬 개발환경

spring:
  # 개발환경에선 로컬 mysql
  datasource:
    url: jdbc:mysql://172.21.138.60:3306/idealstudy?createDatabaseIfNotExist=true
    #    url: jdbc:mysql://172.17.129.27:3306/idealstudy (성진 wsl 주소)

  jpa:
    hibernate:
      ddl-auto: update # 로컬 개발환경에서는 ddl-auto ON
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always # 로컬 개발환경에서는 data.sql 실행
      continue-on-error: true # data.sql 삽입오류시에도 서버 종료하지 않도록

# redis 설정(커스텀)
redis:
  hostname: 172.21.138.60

server:
  backend-domain-url: http://localhost:8080
  backend-domain: localhost
  dev: true
  https: false
