# 실제 운영환경

spring:
  # 운영환경에선 RDS 사용
  datasource:
    url: jdbc:mysql://mysql-db.c128s4yi2c9t.ap-northeast-2.rds.amazonaws.com:3306/idealstudy?createDatabaseIfNotExist=true
    username: manager
    password: manager1234 # rds 는 비밀번호 8자이상 제한

  jpa:
    hibernate:
      ddl-auto: create # 운영환경에서는 ddl-auto OFF
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always # 로컬 개발환경에서는 data.sql 실행
      continue-on-error: true # data.sql 삽입오류시에도 서버 종료하지 않도록

# redis 설정
redis:
  hostname: redis-db
  port: 6379
  password: ""

server:
  frontend-domain-url: https://www.idealstudy.store
  backend-domain-url: http://localhost:8080
  backend-domain: localhost # 추후 배포 환경 도메인으로 변경할 것
  dev: false # dev 일땐 true, false 일땐 true - 시큐리티 설정에서 사용
  https: false # https일 때 true, 아니면 false
