spring:
  application:
    name: mvp

  profiles:
    group:
      development:
        - "dev"
        - "private"
      deployment:
        - "deploy"
        - "private"
      production:
        - "prod"
        - "private" # github 시크릿에서 가져옴
      test:
        - "test"
    active: development

  # 파일 업로드 크기 제어
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 250MB

# 로깅 관련 설정은 logback-spring-server.xml 에서 세밀하게 관리
logging:
  level:
    root: info # 기본 로그는 info level 들이 출력
    org.springframework.security.web: trace # 시큐리티 관한 로그는 trace level 에서 출력
  file: # 스프링 서버에서 남긴 이 로그를 파일에 저장
    name: /var/log/spring-logs/spring-server.log

# 애플리케이션 모니터링을 위해 Actuator 와 Prometheus 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # Prometheus 메트릭 활성화
  metrics:
    export:
      prometheus:
        enabled: true # Prometheus 메트릭 내보내기 활성화

springdoc:
  cache:
    disabled: true
