global:
  resolve_timeout: 5m # alert 가 해결돼도 유지되는 시간

route:
  receiver: "dmsj"
  group_by: ["alertname"] # alertname, instance, job, severity, namespace 등 라벨별로 그룹화하여 일괄전송
  group_wait: 30s # 새로운 alert가 추가되었을 때 대기기간
  group_interval: 5m # 같은 그룹의 alert가 추가되었을 때 전송하기까지 대기기간
  repeat_interval: 4h # alert 가 해결이 되지 않았을때 반복주기

receivers:
  - name: "dmsj"
    slack_configs:
      - channel: "grafana-알림" # 슬랙 알림을 보낼 채널
        send_resolved: true
        api_url: "https://hooks.slack.com/services/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" # 슬랙 웹훅 URL
