name: Notify Slack # Github Actions UI 에 표시될 이름
on: # 트리거 설정 (현재 모든 알림은 깃허브 웹훅에서 직접 설정했으므로 주석처리)
# 다양한 트리거 -> TODO : https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
#  pull_request:
#    types: [opened, closed]
#  issues:
#    types: [opened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "New Event: ${{ github.event_name }}",
              "attachments": [
                {
                  "title": "${{ github.event.issue.title || github.event.pull_request.title }}",
                  "title_link": "${{ github.event.issue.html_url || github.event.pull_request.html_url }}",
                  "text": "Description: ${{ github.event.issue.body || github.event.pull_request.body }}"
                }
              ]
            }
          channel: '#your-channel-name'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
